/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StacksProjectLogsRouteImport } from './routes/stacks/$project/logs'
import { Route as ContainersContainerIdLogsRouteImport } from './routes/containers/$containerId/logs'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StacksProjectLogsRoute = StacksProjectLogsRouteImport.update({
  id: '/stacks/$project/logs',
  path: '/stacks/$project/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContainersContainerIdLogsRoute =
  ContainersContainerIdLogsRouteImport.update({
    id: '/containers/$containerId/logs',
    path: '/containers/$containerId/logs',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/containers/$containerId/logs': typeof ContainersContainerIdLogsRoute
  '/stacks/$project/logs': typeof StacksProjectLogsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/containers/$containerId/logs': typeof ContainersContainerIdLogsRoute
  '/stacks/$project/logs': typeof StacksProjectLogsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/containers/$containerId/logs': typeof ContainersContainerIdLogsRoute
  '/stacks/$project/logs': typeof StacksProjectLogsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/settings'
    | '/containers/$containerId/logs'
    | '/stacks/$project/logs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/settings'
    | '/containers/$containerId/logs'
    | '/stacks/$project/logs'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/settings'
    | '/containers/$containerId/logs'
    | '/stacks/$project/logs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  ContainersContainerIdLogsRoute: typeof ContainersContainerIdLogsRoute
  StacksProjectLogsRoute: typeof StacksProjectLogsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stacks/$project/logs': {
      id: '/stacks/$project/logs'
      path: '/stacks/$project/logs'
      fullPath: '/stacks/$project/logs'
      preLoaderRoute: typeof StacksProjectLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/containers/$containerId/logs': {
      id: '/containers/$containerId/logs'
      path: '/containers/$containerId/logs'
      fullPath: '/containers/$containerId/logs'
      preLoaderRoute: typeof ContainersContainerIdLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  ContainersContainerIdLogsRoute: ContainersContainerIdLogsRoute,
  StacksProjectLogsRoute: StacksProjectLogsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
